### ISSUE TITLE
Work with tvOS?

### ISSUE THREAD

**Issue by davemen** [daprice/iOS-Tactile-Slider#10]
Does it work with tvOS?

**Comment by daprice** [comment]
It's not written with tvOS in mind, no. I consider that out of scope since the purpose of this package is to mimic a native control from iOS/iPadOS, and tvOS has no similar native control to base the behavior on (or which users would be familiar with). I'm also not sure this style of slider makes sense outside of a touchscreen context.

Feel free to fork it if you see value in a tvOS version.
